### ISSUE TITLE
The method 'processTransaction' was called on null.

### ISSUE THREAD

**Issue by snavebaby** [wilburt/rave_flutter#1]
I get this error whenever i try using Ghana Mobile Money Feature.
`The method 'processTransaction' was called on null.
Receiver: null
Tried calling: processTransaction(Instance of 'Payload')`

**Comment by wilburx9** [comment]
Implementation of payments with Ghana Mobile Money is on the way. For the interim, I think I should return a proper error message.

**Comment by snavebaby** [comment]
Well I think you should but I would prefer if you fix it. Can we
collaborate and work on projects?

**Comment by wilburx9** [comment]
I have added the error message pending when the payment method is completed.
About working on other projects, I am sorry I have too much on my plate.

**Comment by snavebaby** [comment]
Sure. Let's keep in touch Thanks.
