### ISSUE TITLE
Help on implementing Mpesa

### ISSUE THREAD

**Issue by thukuwanjiku** [wilburt/rave_flutter#15]
Hi @wilburt  I see from latest commit, that this library works with Mpesa, however when I try to use Mpesa, the rave modal shows error **_This payment mode is currently under development_**. Please help.

![image](https://user-images.githubusercontent.com/17809323/74712530-93870600-5237-11ea-8c80-c8442b9f41f0.png)

**Comment by wilburx9** [comment]
Hi @thukuwanjiku, I have pushed this to pub dev.
