### ISSUE TITLE
Cannot not pass paymentPlan in initializer

### ISSUE THREAD

**Issue by ghost** [wilburt/rave_flutter#2]
The payment plan is not going through on payment for recurring billing . All other data is present on the dashboard. I suspect the key in the initializer is supposed to be payment_plan and not paymentPlan.

**Comment by temiadesina** [comment]
Hi @wilburt possible to help check this out?

**Comment by wilburx9** [comment]
The right key (`payment_plan`) was being used, the issue was that the payment plan wasn't being received in the initialization of the `Payload` object.
Pushing a fix soon.
