### ISSUE TITLE
rave_flutter 0.0.9-alpha+1 returns This payment mode is currently under development

### ISSUE THREAD

**Issue by gilbertmpanga12** [wilburt/rave_flutter#22]
I installed rave_flutter plugin , copied production keys from my flutterwave account but I get This payment mode is currently under development.
1. Payement by card 
2. MPesa
3. Mobile Money (Uganda)
and other payment options all don't work.

Here's my code
`void payWithMobileMoney() async {
Navigator.pop(context);
 var initializer = RavePayInitializer(
       amount: 500, publicKey: 'FLWPUBK-fd13744184c7c4ec3fb622ababef95a5-X', 
        encryptionKey: 'fb7f8d35b0b249431a9db2b0')
      ..country = "UG"
      ..currency = "UGX"
      ..email = "$email"
      ..fName = "$fullName"
      ..narration = 'Subscribe for premium' ?? ''
      ..txRef = 'txRef'
      ..companyName = Text('UNRA')
      ..publicKey = 'FLWPUBK-fd13744184c7c4ec3fb622ababef95a5-X'
      ..encryptionKey = 'fb7f8d35b0b249431a9db2b0'
      ..acceptAccountPayments = true
      ..acceptCardPayments = false
      ..acceptUgMobileMoneyPayments = true
      ..staging = false
      ..isPreAuth = false
      ..displayFee = true;

    // Initialize and get the transaction result
    RaveResult response = await RavePayManager()
        .prompt(context: context, initializer: initializer);
print(response.status);
print(response.rawResponse);
print(response.message);
}`

**Comment by wizlif** [comment]
I have sent in a pull request implementing mobile money UG, hopefully he'll merge it soon [Implement Mobile Money UG](https://github.com/wilburt/rave_flutter/pull/46)

**Comment by wilburx9** [comment]
Any payment method that displays "_This payment mode is currently under development_" has not been implemented by this plugin and it will be in the future.

For Mobile Mobile UG, please follow the updates in #46.
