### ISSUE TITLE
Unhandled Exception: NoSuchMethodError:

### ISSUE THREAD

**Issue by saprahits** [wilburt/rave_flutter#28]
ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]=' was called on null.
    Receiver: null
    Tried calling: []=("orderRef", "1591159969334")
   #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      Payload.toJson (package:rave_flutter/src/dto/payload.dart:142:11)
    #2      new ChargeRequestBody.fromPayload (package:rave_flutter/src/dto/charge_request_body.dart:23:60)
    #3      CardTransactionManager.charge (package:rave_flutter/src/manager/card_transaction_manager.dart:24:50)
    #4      BaseTransactionManager.displayFeeDialog.charge (package:rave_flutter/src/manager/base_transaction_manager.dart:125:12)

**Comment by wilburx9** [comment]
Please, can you paste the construction of the RavePayInitializer?

**Comment by wilburx9** [comment]
Please, I will be closing the issue as it appears they've been no response. Please, feel free to reopen if the issue persists.
