### ISSUE TITLE
displayAmount cannot be null

### ISSUE THREAD

**Issue by emekalites** [wilburt/rave_flutter#3]
Hi,
I  keep getting this error message saying displayAmount cannot be null. If you look at the **validator_utills.dart** file, you will notice the bug there.

It should be 
`if (init.displayAmount == null) return Strings.cannotBeNull("displayAmount");` 
instead of 
`if (init.displayAmount) return Strings.cannotBeNull("displayAmount");` because **init.displayAmount** will always be true or false and not null.

It'll be nice if you could try it out and update the plugin soon. Nice job you did though.

**Comment by wilburx9** [comment]
Thank you for this. I will fix this and do a couple of other cleanups in the [validator file](https://github.com/wilburt/rave_flutter/blob/master/lib/src/common/validator_utills.dart).
