### ISSUE TITLE
How to redirect to another page after successful payment

### ISSUE THREAD

**Issue by yomibrain** [wilburt/rave_flutter#30]
Please i need help regard the above topic, i want users to only have access to a page in my mobile app after making payment with this plugin, like to redirect the successful payment to another page within my app. Thanks

**Comment by wilburx9** [comment]
```
RaveResult response = await RavePayManager()
        .prompt(context: context, initializer: initializer);
if (response.status == RaveStatus.success) {
      Navigator.of(context).push(MaterialPageRoute(builder(context) => AnotherPage());
} else {
      // Do something else
}
```

Does that work?

**Comment by yomibrain** [comment]
Where will pass put the above code?

**Comment by yomibrain** [comment]
When i put it in main.dart
it says: The name 'response' is already define

**Comment by yomibrain** [comment]
Compiler message:
lib/main.dart:219:16: Error: 'response' is already declared in this scope.
    RaveResult response = await RavePayManager()
               ^^^^^^^^
lib/main.dart:213:9: Context: Previous declaration of 'response'.
    var response = await RavePayManager()
        ^^^^^^^^

Compiler message:
lib/main.dart:219:16: Error: 'response' is already declared in this scope.
    RaveResult response = await RavePayManager()
               ^^^^^^^^
lib/main.dart:213:9: Context: Previous declaration of 'response'.
    var response = await RavePayManager()
        ^^^^^^^^

**Comment by yomibrain** [comment]
The above code worked wonderfully well, thanks a bunch boss.
However, how do i include company logo and company name?

**Comment by yomibrain** [comment]
When i press back it takes me to payment page again.... How do i deal with this?

**Comment by wilburx9** [comment]
Replace 
`Navigator.of(context).push(MaterialPageRoute(builder(context) => AnotherPage());` 
with 
`Navigator.of(context).pushReplacement(MaterialPageRoute(builder(context) => AnotherPage());`

**Comment by yomibrain** [comment]
Thanks, i have some other personal questions, how do i connect with you directly?

**Comment by yomibrain** [comment]
Can you help me with this?
When a user clicks on an option within my app,  i  want at that time the app should check that user has subscribed. If not, the app should display payment or subscription page(the user should have 4 different subscription plan to choose from), But if already subscribed then directly to the next page.

**Comment by fixer112** [comment]
Please how do i include meta data

**Comment by wilburx9** [comment]
@yomibrain, 

> Can you help me with this?
> When a user clicks on an option within my app, i want at that time the app should check that user has subscribed. If not, the app should display payment or subscription page(the user should have 4 different subscription plan to choose from), But if already subscribed then directly to the next page.

This question is not related to this plugin, please can you ask this Stackoverflow?
