### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by Heinrich-vanNieuwenhuizen** [wilburt/rave_flutter#39]
I changed the Webviewer with Easywebviewer, the only issue now is that I have no URL callback

**Comment by wilburx9** [comment]
@Heinrich-vanNieuwenhuizen  Please, can you share more information. I don't understand what the issue is.

**Comment by Heinrich-vanNieuwenhuizen** [comment]
Hi Wilburt/Rave_flutter,

If you compile for flutter web, the library webview is not compatible with
flutter web. I had to clone your library edit myself and use a webview that
works with flutter web. (I have an app and web app which I want to use rave
flutter payment). The issue with the library im using is there is no
callback function for the finished payment.

Another issue the subscription option is not working and there is no easy
way to tokenise the credit cards.

Kind Regards,

Heinrich van Nieuwenhuizen

FS Eng (TÜV Rheinland, #15376/ 17, HW/SW Design)
Director


Website: www.ecam.co.za
Cell : (083) 304 1184
Tel: (011) 955 3379/3107/3237
Fax: (011) 955 1053

No.134 Albertina Sisulu Road

Manufacta

Roodepoort
1724

**
Everything in this e-mail and attachments relating to the official business
of ECAM (Pty) Ltd. is proprietary to the company. It is confidential,
legally privileged and protected by law. ECAM (Pty) Ltd. does not own and
endorse any other content. Views and opinions are those of the sender
unless clearly stated as being that of ECAM (Pty) Ltd. The person addressed
in the e-mail is the sole authorized recipient. Please notify the sender
immediately if it has unintentionally reached you and do not read, disclose
or use the content in any way. Whilst all reasonable steps are taken to
ensure the accuracy and integrity of information and data transmitted
electronically and to preserve the confidentiality thereof, no liability or
responsibility whatsoever accepted if information or data is, for whatever
reason corrupted or does not reach its intended destination.

**Comment by wilburx9** [comment]
I currently do not have plans for supporting the web for now. Please, feel free to make a PR if you can implement it successfully.
