### ISSUE TITLE
issue with companyName 

### ISSUE THREAD

**Issue by emekalites** [wilburt/rave_flutter#4]
Hi, 
I tried adding a company name in RavePayInitializer(companyName=''), but this doesnt work because your initializer is requiring a Widget. 
I think you should change it from  `Widget companyName;` to `String companyName;` because of your code here:

    var rightStr =_initializer.companyName ?? _initializer.staging ? Strings.demo : '';
    var rightText = Text(
        rightStr,
        maxLines: 1,
        style: TextStyle(color: Colors.grey[800], fontSize: 16),
    );

As you can see `_initializer.companyName` is being added to the Text widget already so doesnt need to be cast as a widget.

Meanwhile `var rightStr =_initializer.companyName ?? _initializer.staging ? Strings.demo : '';` should have brackets enclosed like this `var rightStr =_initializer.companyName ?? (_initializer.staging ? Strings.demo : '');` because its introducing a bug.

**Comment by wilburx9** [comment]
Thanks for the heads-up, man. This has been fixed.
