### ISSUE TITLE
Uganda Mobile Money Support

### ISSUE THREAD

**Issue by TJMusiitwa** [wilburt/rave_flutter#48]
Hey awesome package, any sort of time scale as to when we could expect support for the 2 remaining unsupported mobile money variants; Uganda and Ghana?
It is a great package but hinders a few of us trying to produce apps that have a market not in the other countries you already support.

**Comment by TJMusiitwa** [comment]
Edit: Found out you have a PR #46  ready to implement one of the payment variants, kindly accept it. Thanks

**Comment by wizlif** [comment]
Hi @TJMusiitwa you can use the implementation by directly including my fork as we wait for @wilburt to merge it
```bash
  # Flutter Wave
  rave_flutter:
    git: git@github.com:wizlif/rave_flutter-1.git
```

I also changed the prompt signature not to return a future but to use a callback instead, so
```dart
var response = await RavePayManager()
        .prompt(context: context, initializer: initializer);
    
    scaffoldKey.currentState
        .showSnackBar(SnackBar(content: Text(response?.message)));
```
Would become
```dart
    RavePayManager().prompt(
        context: context,
        initializer: initializer,
        onTransactionComplete: (RaveResult raveResult) {
          _scaffoldKey.currentState
              .showSnackBar(SnackBar(content: Text(raveResult?.message)));
        });
```

I did this because the `response` wasn't being received by the future. Hence a `null response` in version 1.

**Comment by wizlif** [comment]
I also believe that the same implementation i did for Uganda can work for Ghana as well, since the code implementation is nearly the same ... however i couldn't d this since i have no Ghanaian number to do a live test with.

**Comment by wilburx9** [comment]
@wizlif true, it might work. You can raise a PR for it after #46  is merged.

**Comment by TJMusiitwa** [comment]
Just going to opt to use the now official Flutterwave plugin. Closing comment now
