### ISSUE TITLE
rave payment issue

### ISSUE THREAD

**Issue by emekalites** [wilburt/rave_flutter#5]
Hi,

Whenever i use the plugin for USD card payment, it stays on this display for a long time, is that a problem with flutterwave payment or the plugin. Please check it out.

```dart
var initializer = RavePayInitializer(
        amount: 20.0,
        publicKey: ConfigUtils.ravePublickey(),
        encryptionKey: ConfigUtils.raveEnckey())
      ..country = 'NG'
      ..currency = 'USD'
      ..email = 'your email'
      ..fName = 'john'
      ..lName = 'doe'
      ..narration = 'Transfer'
      ..txRef = 'FL-${DateTime.now().millisecondsSinceEpoch}'
      ..acceptCardPayments = true
      ..staging = true
      ..displayFee = false
      ..acceptAccountPayments = false
      ..displayAmount = false
      ..displayEmail = false
      ..companyLogo = Image.asset(
        'assets/images/logo.png',
        fit: BoxFit.contain,
      )
      ..companyName = 'My Company';
````

I used Test MasterCard 3DSecure authentication
5438 8980 1456 0229
cvv 564
Expiry: 10/20
Pin 3310
otp 12345

![Simulator Screen Shot - iPhone 6s - 2019-11-24 at 11 58 48](https://user-images.githubusercontent.com/6467687/69493693-11927580-0eb2-11ea-9283-764d869a1d20.png)

**Comment by wilburx9** [comment]
For some reason, there are line breaks in the 3DS URL. Now, I am cleaning the URL of all line break and white space characters before loading it.

Thanks for drawing my attention to this.
