### ISSUE TITLE
Unable to build app with Flutter 2.0. Update flutter_svg

### ISSUE THREAD

**Issue by Yonkokilasi** [wilburt/rave_flutter#51]
When I run my app with the new flutter version  , I get this error 
`./../../../.pub-cache/hosted/pub.dartlang.org/rave_flutter-0.0.9-alpha+2/lib/src/ui/payment/rave_pay_widget.dart:2:8: Error: Error when reading '../../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/flutter_svg.dart': No such file or directory`
This is because I updated my flutter svg package to the new one which is flutter_svg: ^0.19.3
The previous version of flutter svg is not compatible with Flutter 2.0
 Fix is to upgrade flutter svg in your pubspec

**Comment by AdnanKazi** [comment]
@Yonkokilasi Have you got any workaround or have solved it ?

**Comment by Yonkokilasi** [comment]
> @Yonkokilasi Have you got any workaround or have solved it ?

Checkout the changes in my pull request, they solve the issue.
Upgrade flutter svg in the rave flutter files
`flutter_svg: ^0.19.3`

**Comment by wilburx9** [comment]
For updates on Flutter 2.0, see #61
