### ISSUE TITLE
I keep getting this error when trying to user rave_flutter

### ISSUE THREAD

**Issue by kcibdev** [wilburt/rave_flutter#54]
Everything I try to install `tripledes: ^2.1.0` I keep getting the error
>Because no versions of tripledes match 2.1.0 and no versions of tripledes match >2.1.0 <3.0.0, tripledes ^2.1.0 is forbidden. 
>So, because **** depends on tripledes ^2.1.0, version solving failed.
pub get failed (1; So, because **** depends on tripledes ^2.1.0, version solving failed.)

It happens every single times and i dont know what caused it, cause am trying to use `rave_flutter: ^0.0.9-alpha+2` which depends on tripledes and its not working because of this error.
What is the problem

This are my depencies:
>**dependencies:**
     google_sign_in: ^4.5.6
    firebase_auth:
    provider: ^4.3.2+3
    flutter_switch: ^0.2.0
    cached_network_image: ^2.5.0
    shared_preferences: ^0.5.12+4
    image_picker: ^0.6.7+17
    flutter_image_compress: ^0.7.0
    image_cropper: ^1.3.1
    intl: ^0.16.1
    http: ^0.12.2
    transparent_image: ^1.0.0
    country_state_city_picker: ^1.2.7
    animations: ^1.1.2
    smooth_star_rating: ^1.1.1
    csc_picker: ^0.0.4
    firebase_core: ^0.7.0
    rave_flutter: ^0.0.9-alpha+2
    async: ^2.4.2
   dio: ^3.0.10
    equatable: ^1.2.5
    flutter_svg: ^0.19.2+1
    get_it: ^5.0.2
    meta: ^1.2.4
    tripledes: ^2.1.0
    webview_flutter: ^1.0.7
    flutter:
      sdk: flutter

**Comment by wilburx9** [comment]
This should be fixed after the support for Flutter 2. #61 has the latest updates on Flutter 2.0 support.
