### ISSUE TITLE
flutter_svg-0.18.1 problem in flutter 2.0.0

### ISSUE THREAD

**Issue by AdnanKazi** [wilburt/rave_flutter#55]
I have just updated my flutter SDK version to 2.0.0 and I run my project I got this error please Fix this issue asap 

Error
```
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^        
../../../Development/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {                        
                ^^^^^^^^                                                
FAILURE: Build failed with an exception.                                
* Where:                                                                
Script '/Users/helpmac/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/Users/helpmac/Development/flutter/bin/flutter'' finished with non-zero exit value 1
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org                              
BUILD FAILED in 50s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        50.9s
Exception: Gradle task assembleDebug failed with exit code 1
```
Flutter doctor
```
[✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15 19A583 darwin-x64, locale en-GB)
    • Flutter version 2.0.0 at /Users/helpmac/Development/flutter
    • Framework revision 60bd88df91 (9 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/helpmac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/helpmac/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    ! Xcode 11.0.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0
[✓] Connected device (3 available)
    • IN Note1 (mobile) • BS7746M4KN1120012228                 • android-arm64  • Android 10 (API 29)
    • iPhone X (mobile) • 3EF95060-4336-4017-9BE0-73CB5C3CE227 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 89.0.4389.82
! Doctor found issues in 1 category.
```

**Comment by Yonkokilasi** [comment]
This issue is similar to / caused by : https://github.com/wilburt/rave_flutter/issues/51

**Comment by Yonkokilasi** [comment]
> I have just updated my flutter SDK version to 2.0.0 and I run my project I got this error please Fix this issue asap
> 
> Error
> 
> ```
> ../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.1/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
>         context != null ? Localizations.localeOf(context, nullOk: true) : null,
>                                                           ^^^^^^        
> ../../../Development/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
>   static Locale localeOf(BuildContext context) {                        
>                 ^^^^^^^^                                                
> FAILURE: Build failed with an exception.                                
> * Where:                                                                
> Script '/Users/helpmac/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991
> * What went wrong:                                                      
> Execution failed for task ':app:compileFlutterBuildDebug'.              
> > Process 'command '/Users/helpmac/Development/flutter/bin/flutter'' finished with non-zero exit value 1
> * Try:                                                                  
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org                              
> BUILD FAILED in 50s                                                     
> Running Gradle task 'assembleDebug'...                                  
> Running Gradle task 'assembleDebug'... Done                        50.9s
> Exception: Gradle task assembleDebug failed with exit code 1
> ```
> 
> Flutter doctor
> 
> ```
> [✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15 19A583 darwin-x64, locale en-GB)
>     • Flutter version 2.0.0 at /Users/helpmac/Development/flutter
>     • Framework revision 60bd88df91 (9 days ago), 2021-03-03 09:13:17 -0800
>     • Engine revision 40441def69
>     • Dart version 2.12.0
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/helpmac/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = /Users/helpmac/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> [!] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.0, Build version 11A420a
>     ! Xcode 11.0.0 out of date (12.0.1 is recommended).
>       Download the latest version or update via the Mac App Store.
>     • CocoaPods version 1.10.1
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> [✓] VS Code (version 1.54.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.20.0
> [✓] Connected device (3 available)
>     • IN Note1 (mobile) • BS7746M4KN1120012228                 • android-arm64  • Android 10 (API 29)
>     • iPhone X (mobile) • 3EF95060-4336-4017-9BE0-73CB5C3CE227 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
>     • Chrome (web)      • chrome                               • web-javascript • Google Chrome 89.0.4389.82
> ! Doctor found issues in 1 category.
> ```

This issue is similar to / caused by : https://github.com/wilburt/rave_flutter/issues/51

**Comment by AdnanKazi** [comment]
@Yonkokilasi Can you explain how can i use your branch code

**Comment by Yonkokilasi** [comment]
> @Yonkokilasi Can you explain how can i use your branch code

Go to your .pubcache . Locate the rave flutter sdk .
Open it in your preferred IDE
Go to it's pub spec and update flutter_svg to 0.19.3 (latest flutter svg)
@AdnanKazi

**Comment by AdnanKazi** [comment]
ok but it will not solve the problem permanently if execute command pub get then still old version will come maybe I think I should wait for your pull request to approve 

Also, I had conversation with the flutterwave team they recommend using there official SDK https://pub.dev/packages/flutterwave

**Comment by Yonkokilasi** [comment]
Solution will remain in place until you delete your .pubcache or you
upgrade the package otherwise it will always reference the local version
you changed .

**Comment by AdnanKazi** [comment]
@Yonkokilasi This will really help but @wilburt should take some time to make it permanently  
In my case there were others packages as well which needs to be updated

**Comment by nkenna** [comment]
`dependency_overrides:
  flutter_svg: ^0.19.3`

This should show your problem for now.

**Comment by wilburx9** [comment]
For updates on Flutter 2.0, see #61
