### ISSUE TITLE
@Rioland  you have to make sure that `..staging=false` because when it is `true` you must provide the sendBox mode public key which is defferent from the live mode public key

### ISSUE THREAD

**Issue by Dagitpam** [wilburt/rave_flutter#60]
@Rioland  you have to make sure that `..staging=false` because when it is `true` you must provide the sendBox mode public key which is defferent from the live mode public key

_Originally posted by @fried19 in https://github.com/wilburt/rave_flutter/issues/34#issuecomment-686981969_'

How can I make the staging mode to false?

**Comment by wilburx9** [comment]
Please, see the ReadMe.
